### ISSUE TITLE
add an 404 page not found for invalid urls.

### ISSUE THREAD

**Issue by mann27** [mann27/News24x7-Client#35] opened 2020-09-16 10:41 UTC

**Comment by AshutoshDash1999** [comment] 2020-09-17 05:50
Hey @mann27, can I take up this issue?

**Comment by mann27** [comment] 2020-09-17 07:39
Yes, go ahead. The 404 page should include the navbar, footer, center image of the 404 sign(anyone you like) and a link back to the home page.

**Comment by AshutoshDash1999** [comment] 2020-09-17 09:44
hey @mann27, thank you for assigning this task to me, I have some query as follows:
1. Since I'm not familiar with React, can I design the page using HTML, CSS and JS?
2. do you have any predefined design for the webpage?

**Comment by mann27** [comment] 2020-09-17 11:30
In the project we have used react.js. so i suggest you to take some basic tutorials for the same. And you can use css for the styling part.

Try making the design of the page similar to that of other pages as of now. ( checkout the  app for this) 

 To run the app
- install node.js
- go to the root directory in cmd/terminal
- `npm i`
- `npm start`

**Comment by AshutoshDash1999** [comment] 2020-09-19 07:14
Ok, let me try.
Can I take some time creating proposal for this project before moving on with the project?

**Comment by mann27** [comment] 2020-09-19 11:54
Okay

**Comment by AshutoshDash1999** [comment] 2020-09-21 06:38
Hey @mann27 , I'm really sorry to inform you that I can't work on this issue. Hope you will find someone with the right skill set.

**Comment by iemprashant** [comment] 2020-09-26 05:20
Hey, @mann27  I would like to take this issue.

**Comment by mann27** [comment] 2020-09-26 05:49
@iemprashant Sure go ahead!

**Comment by iemprashant** [comment] 2020-09-26 07:02
![image](https://user-images.githubusercontent.com/53941491/94332506-6da6b880-fff3-11ea-847a-9b7fadae7a9e.png)

I have added the 404 page and its working but due to UI issue it is somewhat hidden, so may I submit PR and left this for UI enhancement?

**Comment by Shubh1815** [comment] 2020-10-01 07:13
If the issue is still open then can I work on it???

**Comment by mann27** [comment] 2020-10-01 07:27
Yes, @Shubh1815 go ahead!

**Closed** 2020-10-01 14:48 UTC
Labels: SLoP-75, enhancement
